export const KHR_SUPERCOMPRESSION_NONE = 0;

export const KHR_DF_VENDORID_KHRONOS = 0;
export const KHR_DF_KHR_DESCRIPTORTYPE_BASICFORMAT = 0;
export const KHR_DF_VERSION = 2;
export const KHR_DF_MODEL_RGBSDA = 1;
export const KHR_DF_PRIMARIES_BT709 = 1;
export const KHR_DF_TRANSFER_LINEAR = 1;
export const KHR_DF_CHANNEL_RGBSDA_RED = 0;
export const KHR_DF_CHANNEL_RGBSDA_GREEN = 1;
export const KHR_DF_CHANNEL_RGBSDA_BLUE = 2;
export const KHR_DF_CHANNEL_RGBSDA_ALPHA = 15;
export const KHR_DF_SAMPLE_DATATYPE_SIGNED = 0x40;
export const KHR_DF_SAMPLE_DATATYPE_FLOAT = 0x80;

export const VK_FORMAT_R8_UNORM = 9;
export const VK_FORMAT_R8G8B8A8_UNORM = 37;
export const VK_FORMAT_R16G16B16A16_SFLOAT = 97;
export const VK_FORMAT_BC4_UNORM_BLOCK = 139;
export const VK_FORMAT_EAC_R11_UNORM_BLOCK = 153;
export const VK_FORMAT_ASTC_4x4_UNORM_BLOCK = 157;
