// Generated by site/scripts/bake-chorus.mts. Do not edit.
import face0 from '../assets/chorus-latin.font.glb?url';
import face1 from '../assets/chorus-arabic.font.glb?url';
import face2 from '../assets/chorus-hebrew.font.glb?url';
import face3 from '../assets/chorus-devanagari.font.glb?url';
import face4 from '../assets/chorus-bengali.font.glb?url';
import face5 from '../assets/chorus-gurmukhi.font.glb?url';
import face6 from '../assets/chorus-gujarati.font.glb?url';
import face7 from '../assets/chorus-oriya.font.glb?url';
import face8 from '../assets/chorus-tamil.font.glb?url';
import face9 from '../assets/chorus-telugu.font.glb?url';
import face10 from '../assets/chorus-kannada.font.glb?url';
import face11 from '../assets/chorus-malayalam.font.glb?url';
import face12 from '../assets/chorus-sinhala.font.glb?url';
import face13 from '../assets/chorus-thai.font.glb?url';
import face14 from '../assets/chorus-lao.font.glb?url';
import face15 from '../assets/chorus-khmer.font.glb?url';
import face16 from '../assets/chorus-myanmar.font.glb?url';
import face17 from '../assets/chorus-georgian.font.glb?url';
import face18 from '../assets/chorus-armenian.font.glb?url';
import face19 from '../assets/chorus-ethiopic.font.glb?url';
import face20 from '../assets/chorus-japanese.font.glb?url';
import face21 from '../assets/chorus-korean.font.glb?url';

/** Fallback order: Latin first, CJK last, scripted faces in between. */
export const CHORUS_URLS = [
  face0,
  face1,
  face2,
  face3,
  face4,
  face5,
  face6,
  face7,
  face8,
  face9,
  face10,
  face11,
  face12,
  face13,
  face14,
  face15,
  face16,
  face17,
  face18,
  face19,
  face20,
  face21,
] as const;
