pub const RESPONSE_MAGIC: &str = "PMBM";
pub const RESPONSE_HEADER_BYTES: u32 = 16;
pub const RESPONSE_STATUS_OFFSET: u32 = 4;
pub const RESPONSE_METADATA_LEN_OFFSET: u32 = 8;
pub const RESPONSE_ARTIFACT_LEN_OFFSET: u32 = 12;
pub const RESPONSE_PAYLOAD_OFFSET: u32 = 16;
pub const RESPONSE_SUCCESS_STATUS: u32 = 0;
