/** Renderer-neutral engine construction and integration contracts. */
export { createTextRuntime, type TextRuntime, type TextRuntimeOptions } from './text-runtime.js';
export {
  TextEngineHost,
  TextEngineStatusError,
  textEngineStatusErrorDetails,
  type HostFontBinding,
  type HostFontStackBinding,
  type HostMaterialBinding,
  type HostPolicy,
  type HostPolicyFactory,
  type HostResourceBinding,
  type HostTransformBinding,
  type TextEngineHostOptions,
  type TextEngineFault,
  type TextEngineStatusCode,
  type TextEngineStatusDetails,
} from './core/host.js';
export {
  TextEngineBackpressureError,
  TextEngineSessionDisposedError,
  TextEngineTransportCapacityError,
  TextEngineTransportError,
  type AsyncPlanCandidate,
  type AsyncPlanTarget,
  type AsyncPlanTargetResult,
  type AsyncTextEngineSession,
  type BorrowedTextEngineRenderPlan,
  type OwnedTextEngineRenderPlan,
  type PlanAcceptance,
  type PlanCandidate,
  type PlanOrigin,
  type PlanTarget,
  type PlanTargetControl,
  type PortablePayloadIdentity,
  type PortablePayloadLease,
  type ResolvedPortablePayload,
  type RenderPlanTableName,
  type ResolvedPlanPayload,
  type ResolvedPlanTransform,
  type SessionFor,
  type SynchronousTextEngineSession,
  type TextEngineExclusionInput,
  type TextEngineFlowInput,
  type TextEngineFlowRegionInput,
  type TextEngineFormattedText,
  type TextEngineInlineObjectInput,
  type TextEngineLimits,
  type TextEnginePublishOptions,
  type TextEngineRegionInput,
  type TextEngineRenderPlanReader,
  type TextEngineSessionOptions,
  type TextEngineSpan,
  type TextEngineText,
  type TextEngineTextInput,
  type TextEngineTextOptions,
  type TextEngineTextUpdate,
  type TextPlanTarget,
} from './core/retained-session.js';
export { TextEngineRenderPlanView, type RenderPlanTable } from './core/plan-view.js';
export {
  readTextEngineBuffer,
  readTextEngineDraw,
  readTextEnginePatch,
  readTextEnginePrimitive,
  readTextEngineResource,
  readTextEngineRetirement,
  type RenderPlanBufferId,
  type RenderPlanClipId,
  type RenderPlanDrawId,
  type RenderPlanPrimitiveId,
  type RenderPlanResourceId,
  type RenderPlanSemanticId,
  type RenderPlanTransformId,
  type TextEngineAllocatePatch,
  type TextEngineBufferBinding,
  type TextEngineBufferRecord,
  type TextEngineCopyPatch,
  type TextEngineDrawRecord,
  type TextEngineFillPatch,
  type TextEnginePatchRecord,
  type TextEnginePrimitiveKind,
  type TextEnginePrimitiveRecord,
  type TextEngineResourceAction,
  type TextEngineResourceRecord,
  type TextEngineRetirePatch,
  type TextEngineRetirementKind,
  type TextEngineRetirementRecord,
  type TextEngineScalarType,
  type TextEngineWritePatch,
} from './core/plan-view.js';
export {
  compileFontBinding,
  schemaFieldTable,
  emptyFontBindingTable,
  fontBindingBytes,
  fontBindingResources,
  type BindingResource,
  type FontBindingDescriptor,
  type FontBindingFieldTable,
} from './core/font-binding.js';
export {
  compileRasterFont,
  createRasterPolicyProgram,
  registerRasterPlanProgram,
  resolveRasterPlanProgram,
  type CompiledRasterFont,
  type RasterPlanProgram,
  type RasterPlanProgramFontCompiler,
  type RasterFontBinding,
  type RasterPolicyBodyFactory,
  type RasterPolicyProgramOptions,
  type RasterPolicySystem,
} from './core/raster-plan-program.js';
export {
  compileRenderPolicy,
  createProgram,
  id,
  programContext,
  programId,
  renderWireId,
  resourceId,
  RenderWireIdentityRegistry,
  selectPolicyCapabilitySet,
  stores,
  techniqueId,
  type PolicyAllocationMode,
  type PolicyBuffer,
  type PolicyBufferId,
  type PolicyCapability,
  type PolicyCapabilitySet,
  type PolicyCapabilitySetSelection,
  type PolicyDescriptor,
  type PolicyInput,
  type PolicyInputScope,
  type MaterialHandle,
  type PolicyOperation,
  type PolicyProgram,
  type PolicyScalarType,
  type PolicyTransformMode,
  type ProgramContext,
  type RenderProgramId,
  type RenderResourceId,
  type RenderTechniqueId,
  type ResourceHandle,
} from './core/render-policy.js';
export {
  definePolicyBuffers,
  defineTechniqueGeometryKind,
  defineTechniqueSchema,
  schemaPolicyBuffers,
  type AnyTechniqueSchema,
  type PolicyBufferDeclaration,
  type PolicyBufferDeclarations,
  type PolicyScalarKind,
  type TechniqueBindingDeclaration,
  type TechniqueBufferResourceDeclaration,
  type TechniqueCustomGeometryKind,
  type TechniqueGeometryCoordinates,
  type TechniqueGeometryDeclaration,
  type TechniqueGeometryKind,
  type TechniqueGeometryResourceDeclaration,
  type TechniqueRenderDeclaration,
  type TechniqueResourceDeclaration,
  type TechniqueResourceDeclarations,
  type TechniqueResourceGroupDeclaration,
  type TechniqueResourceGroupMembers,
  type TechniqueSchema,
  type TechniqueSchemaDeclaration,
  type TechniqueSuppliedGeometryKind,
  type TechniqueTextureResourceDeclaration,
  type TechniqueTextureArrayResourceDeclaration,
} from './core/technique-schema.js';
export {
  assertPortableResource,
  assertPortableVertexSemantic,
  definePortableVertexSemantic,
  portableResourceKinds,
  portableTextureFormats,
  portableTopologies,
  type PortableAccessor,
  type PortableBufferPayload,
  type PortableBufferView,
  type PortableComponentType,
  type PortableCustomVertexSemantic,
  type PortableDrawRange,
  type PortableGeometryIndices,
  type PortableGeometryPayload,
  type PortableLeafResource,
  type PortableResource,
  type PortableResourceGroupPayload,
  type PortableResourceKind,
  type PortableTexturePayload,
  type PortableTextureArrayPayload,
  type PortableTextureFormat,
  type PortableTopology,
  type PortableVertexAttribute,
  type PortableVertexInput,
  type PortableVertexSemantic,
} from './core/portable-resources.js';
export {
  f32,
  policyProgram,
  techniqueProgram,
  u32,
  type CompiledPolicyProgramBody,
  type PolicyColorChannels,
  type PolicyF32Value,
  type PolicyF32Expressions,
  type PolicyProgramBuilder,
  type PolicyProgramOptions,
  type PolicyProgramSystemBuffers,
  type PolicyProgramSemantics,
  type PolicyU32Value,
  type PolicyU32Expressions,
  type TechniquePolicyProgramBuilder,
  type TechniquePolicyStores,
} from './core/policy-program.js';
