/**
 * The renderer-neutral text engine: everything a custom renderer integration needs to
 * load fonts into one Wasm shaper, serialize frame updates, and consume revisioned
 * render plans. `@pmndrs/glyph/three` is implemented on exactly this surface.
 */
export {
  createRuntimeShaper,
  type RuntimeShaper,
  type RuntimeShaperMemoryReport,
  type RuntimeShaperOptions,
  type TextShaperWasmSource,
} from './shaper.js';
export { textRuntimeShaper } from './text-runtime.js';
export { createTextRuntime, type TextRuntime, type TextRuntimeOptions } from './text-runtime.js';
export {
  acquireFontSelectionForRuntime,
  assertFontSelectionForRuntime,
  concreteFonts,
  observeLoadedFontDispose,
  releaseFontSelection,
} from './loaded-font.js';
export {
  TextEngineHost,
  TextEngineSession,
  TextEngineStatusError,
  type TextEngineFault,
  type HostFontBinding,
  type HostFontStackBinding,
  type HostPolicy,
  type TextEngineHostOptions,
  type TextEnginePublication,
  type TextEngineSessionOptions,
} from './core/host.js';
export {
  compileTextEngineFrameUpdate,
  type TextEngineConstraint,
  type TextEngineDecoration,
  type TextEngineExclusion,
  type TextEngineFeature,
  type TextEngineFrameLimits,
  type TextEngineFlowVertex,
  type TextEngineFrameUpdate,
  type TextEngineInlineObject,
  type TextEngineParagraphMutation,
  type TextEngineRegion,
  type TextEngineStyleMutation,
  type TextEngineStyleValue,
  type TextEngineTextMutation,
} from './core/frame-wire.js';
export { TextEngineRenderPlanView, type RenderPlanTable } from './core/plan-view.js';
export {
  readTextEngineBuffer,
  readTextEnginePatch,
  readTextEngineResource,
  readTextEngineRetirement,
  type TextEngineBufferRecord,
  type TextEnginePatchRecord,
  type TextEngineResourceRecord,
  type TextEngineRetirementRecord,
} from './core/plan-view.js';
export {
  assertOwnedTextEnginePublication,
  TextEnginePublicationExpiredError,
  type OwnedTextEnginePublication,
} from './core/retention.js';
export { readTextEngineLayouts, readTextEngineMeasurements } from './core/layout-query-view.js';
export {
  compileFontBinding,
  schemaFieldTable,
  emptyFontBindingTable,
  fontBindingBytes,
  fontBindingResources,
  type BindingResource,
  type FontBindingDescriptor,
  type FontBindingFieldTable,
} from './core/font-binding.js';
export {
  compileRasterFont,
  createRasterPolicyProgram,
  registerRasterPlanProgram,
  resolveRasterPlanProgram,
  type CompiledRasterFont,
  type RasterPlanProgram,
  type RasterPlanProgramFontCompiler,
  type RasterFontBinding,
  type RasterPolicyBodyFactory,
  type RasterPolicyProgramOptions,
  type RasterPolicySystem,
} from './core/raster-plan-program.js';
export { compileLoadedRasterFont } from './core/raster-plan-program.js';
export {
  compileRenderPolicy,
  createProgram,
  id,
  programContext,
  programId,
  renderWireId,
  resourceId,
  RenderWireIdentityRegistry,
  selectPolicyCapabilitySet,
  stores,
  techniqueId,
  type PolicyAllocationMode,
  type PolicyBuffer,
  type PolicyBufferId,
  type PolicyCapabilitySet,
  type PolicyCapabilitySetSelection,
  type PolicyDescriptor,
  type PolicyInput,
  type PolicyInputScope,
  type PolicyOperation,
  type PolicyProgram,
  type PolicyTransformMode,
  type ProgramContext,
  type RenderProgramId,
  type RenderResourceId,
  type RenderTechniqueId,
  type FontBindingHandle,
  type ExclusionId,
  type FlowThreadId,
  type FontStackHandle,
  type GlyphId,
  type GlyphIdKind,
  type InlineObjectId,
  type MaterialHandle,
  type ParagraphId,
  type PolicyHandle,
  type RegionId,
  type ResourceHandle,
  type StyleId,
  type TextEngineSessionHandle,
} from './core/render-policy.js';
export {
  definePolicyBuffers,
  defineTechniqueGeometryKind,
  defineTechniqueSchema,
  schemaPolicyBuffers,
  type AnyTechniqueSchema,
  type PolicyBufferDeclaration,
  type PolicyBufferDeclarations,
  type PolicyScalarKind,
  type TechniqueBindingDeclaration,
  type TechniqueBufferResourceDeclaration,
  type TechniqueCustomGeometryKind,
  type TechniqueGeometryCoordinates,
  type TechniqueGeometryDeclaration,
  type TechniqueGeometryKind,
  type TechniqueGeometryResourceDeclaration,
  type TechniqueRenderDeclaration,
  type TechniqueResourceDeclaration,
  type TechniqueResourceDeclarations,
  type TechniqueResourceGroupDeclaration,
  type TechniqueResourceGroupMembers,
  type TechniqueSchema,
  type TechniqueSchemaDeclaration,
  type TechniqueSuppliedGeometryKind,
  type TechniqueTextureResourceDeclaration,
  type TechniqueTextureArrayResourceDeclaration,
} from './core/technique-schema.js';
export {
  assertPortableResource,
  assertPortableVertexSemantic,
  definePortableVertexSemantic,
  portableResourceKinds,
  portableTextureFormats,
  portableTopologies,
  type PortableAccessor,
  type PortableBufferPayload,
  type PortableBufferView,
  type PortableComponentType,
  type PortableCustomVertexSemantic,
  type PortableDrawRange,
  type PortableGeometryIndices,
  type PortableGeometryPayload,
  type PortableLeafResource,
  type PortableResource,
  type PortableResourceGroupPayload,
  type PortableResourceKind,
  type PortableTexturePayload,
  type PortableTextureArrayPayload,
  type PortableTextureFormat,
  type PortableTopology,
  type PortableVertexAttribute,
  type PortableVertexInput,
  type PortableVertexSemantic,
} from './core/portable-resources.js';
export {
  f32,
  policyProgram,
  techniqueProgram,
  u32,
  type CompiledPolicyProgramBody,
  type PolicyColorChannels,
  type PolicyF32Value,
  type PolicyF32Expressions,
  type PolicyProgramBuilder,
  type PolicyProgramOptions,
  type PolicyProgramSystemBuffers,
  type PolicyProgramSemantics,
  type PolicyU32Value,
  type PolicyU32Expressions,
  type TechniquePolicyProgramBuilder,
  type TechniquePolicyStores,
} from './core/policy-program.js';
export { textShaperAbi } from './generated/text-shaper-abi.js';
export type { ParagraphOptions, ParagraphUpdate } from './paragraph.js';
export { Paragraph } from './paragraph.js';
