/** Renderer-neutral engine construction and integration contracts. */
export { createGlyphEngine, type GlyphEngine, type GlyphEngineOptions } from './glyph-engine.js';
export {
  GlyphBackend,
  GlyphEngineStatusError,
  glyphEngineStatusErrorDetails,
  type BackendFontBinding,
  type BackendFontStackBinding,
  type BackendMaterialBinding,
  type BackendPolicy,
  type BackendPolicyFactory,
  type BackendResourceBinding,
  type BackendTransformBinding,
  type GlyphBackendOptions,
  type GlyphEngineFault,
  type GlyphEngineStatusCode,
  type GlyphEngineStatusDetails,
} from './core/backend.js';
export {
  RenderPlannerBackpressureError,
  RenderPlannerDisposedError,
  PlanTransportCapacityError,
  PlanTransportError,
  type AsyncPlanCandidate,
  type AsyncPlanTarget,
  type AsyncPlanTargetResult,
  type AsyncRenderPlanner,
  type BorrowedRenderPlan,
  type OwnedRenderPlan,
  type PlanAcceptance,
  type PlanCandidate,
  type PlanOrigin,
  type PlanTarget,
  type PlanTargetControl,
  type PortablePayloadIdentity,
  type PortablePayloadLease,
  type ResolvedPortablePayload,
  type RenderPlanTableName,
  type ResolvedPlanPayload,
  type ResolvedPlanTransform,
  type RenderPlannerFor,
  type RenderPlanner,
  type RetainedTextExclusionInput,
  type RetainedTextFlowInput,
  type RetainedTextFlowRegionInput,
  type RetainedFormattedText,
  type RetainedTextInlineObjectInput,
  type RenderPlannerLimits,
  type RenderPlannerPublishOptions,
  type RetainedTextRegionInput,
  type RenderPlanReader,
  type RenderPlannerOptions,
  type RetainedTextSpan,
  type RetainedText,
  type RetainedTextInput,
  type RetainedTextOptions,
  type RetainedTextUpdate,
  type RenderPlanTarget,
} from './core/render-planner.js';
export { RenderPlanView, type RenderPlanTable } from './core/plan-view.js';
export {
  readRenderPlanBuffer,
  readRenderPlanDraw,
  readRenderPlanPatch,
  readRenderPlanPrimitive,
  readRenderPlanResource,
  readRenderPlanRetirement,
  type RenderPlanBufferId,
  type RenderPlanClipId,
  type RenderPlanDrawId,
  type RenderPlanPrimitiveId,
  type RenderPlanResourceId,
  type RenderPlanSemanticId,
  type RenderPlanTransformId,
  type RenderPlanAllocatePatch,
  type RenderPlanBufferBinding,
  type RenderPlanBufferRecord,
  type RenderPlanCopyPatch,
  type RenderPlanDrawRecord,
  type RenderPlanFillPatch,
  type RenderPlanPatchRecord,
  type RenderPlanPrimitiveKind,
  type RenderPlanPrimitiveRecord,
  type RenderPlanResourceAction,
  type RenderPlanResourceRecord,
  type RenderPlanRetirePatch,
  type RenderPlanRetirementKind,
  type RenderPlanRetirementRecord,
  type RenderPlanScalarType,
  type RenderPlanWritePatch,
} from './core/plan-view.js';
export {
  compileFontBinding,
  schemaFieldTable,
  emptyFontBindingTable,
  fontBindingBytes,
  fontBindingResources,
  type BindingResource,
  type FontBindingDescriptor,
  type FontBindingFieldTable,
} from './core/font-binding.js';
export {
  compileRasterFont,
  createRasterPolicyProgram,
  readCompiledRasterFont,
  registerRasterPlanProgram,
  resolveRasterPlanProgram,
  type CompiledRasterFont,
  type CompiledRasterFontResource,
  type CompiledRasterFontView,
  type RasterPlanProgram,
  type RasterPlanProgramFontCompiler,
  type RasterFontBinding,
  type RasterPolicyBodyFactory,
  type RasterPolicyProgramOptions,
  type RasterPolicySystem,
} from './core/raster-plan-program.js';
export {
  compileRenderPolicy,
  createProgram,
  id,
  programContext,
  selectPolicyCapabilitySet,
  stores,
  type Id,
  type IdFactory,
  type PolicyAllocationMode,
  type PolicyBuffer,
  type PolicyBufferId,
  type PolicyCapability,
  type PolicyCapabilitySet,
  type PolicyCapabilitySetSelection,
  type PolicyDescriptor,
  type PolicyInput,
  type PolicyInputScope,
  type MaterialHandle,
  type PolicyOperation,
  type PolicyProgram,
  type PolicyScalarType,
  type PolicyTransformMode,
  type ProgramContext,
  type RenderProgramId,
  type RenderIdFactory,
  type RenderResourceId,
  type RenderTechniqueId,
  type ResourceHandle,
} from './core/render-policy.js';
export {
  definePolicyBuffers,
  defineTechniqueGeometryKind,
  defineTechniqueSchema,
  schemaPolicyBuffers,
  type AnyTechniqueSchema,
  type PolicyBufferDeclaration,
  type PolicyBufferDeclarations,
  type PolicyScalarKind,
  type TechniqueBindingDeclaration,
  type TechniqueBufferResourceDeclaration,
  type TechniqueCustomGeometryKind,
  type TechniqueGeometryCoordinates,
  type TechniqueGeometryDeclaration,
  type TechniqueGeometryKind,
  type TechniqueGeometryResourceDeclaration,
  type TechniqueRenderDeclaration,
  type TechniqueResourceDeclaration,
  type TechniqueResourceDeclarations,
  type TechniqueResourceGroupDeclaration,
  type TechniqueResourceGroupMembers,
  type TechniqueSchema,
  type TechniqueSchemaDeclaration,
  type TechniqueSuppliedGeometryKind,
  type TechniqueTextureResourceDeclaration,
  type TechniqueTextureArrayResourceDeclaration,
} from './core/technique-schema.js';
export {
  assertPortableResource,
  assertPortableVertexSemantic,
  definePortableVertexSemantic,
  portableResourceKinds,
  portableTextureFormats,
  portableTopologies,
  type PortableAccessor,
  type PortableBufferPayload,
  type PortableBufferView,
  type PortableComponentType,
  type PortableCustomVertexSemantic,
  type PortableDrawRange,
  type PortableGeometryIndices,
  type PortableGeometryPayload,
  type PortableLeafResource,
  type PortableResource,
  type PortableResourceGroupPayload,
  type PortableResourceKind,
  type PortableTexturePayload,
  type PortableTextureArrayPayload,
  type PortableTextureFormat,
  type PortableTopology,
  type PortableVertexAttribute,
  type PortableVertexInput,
  type PortableVertexSemantic,
} from './core/portable-resources.js';
export {
  f32,
  policyProgram,
  techniqueProgram,
  u32,
  type CompiledPolicyProgramBody,
  type PolicyColorChannels,
  type PolicyF32Value,
  type PolicyF32Expressions,
  type PolicyProgramBuilder,
  type PolicyProgramOptions,
  type PolicyProgramSystemBuffers,
  type PolicyProgramSemantics,
  type PolicyU32Value,
  type PolicyU32Expressions,
  type TechniquePolicyProgramBuilder,
  type TechniquePolicyStores,
} from './core/policy-program.js';
